### ISSUE TITLE
Could you consider adding the following repo?

### ISSUE THREAD

**Issue by shiba24** [hzwer/Awesome-Optical-Flow#1]
Hi, @hzwer ,

could you add the following entry?

ECCV 2022 (Oral), [Secrets of Event-based Optical Flow](https://github.com/tub-rip/event_based_optical_flow), stars 71 (as of May 2023)

This is work for event cameras, not frame cameras, but I think it's useful.

**Comment by hzwer** [comment]
Sure! If you know other related papers, I am happy to add them.
